#!/bin/sh
# Cut a GitHub release: signed tag, signed upstream tarball, the two .debs.
#
# This runs on a workstation and never in CI, and that is the whole design.
# The key that signs here is the key that signs uploads to Debian -- selected
# by the address in debian/changelog, same as dpkg-buildpackage picks it -- so
# it must not live in a GitHub Actions secret. A compromise of the repository
# would otherwise be a compromise of the Debian identity.
#
# What lands on the release, and why each one is there:
#
#   hadith-<upstream>.tar.gz       the orig tarball under its upstream name.
#   hadith-<upstream>.tar.gz.asc   debian/watch finds this pair, and uscan
#                                  verifies it against
#                                  debian/upstream/signing-key.asc. This is the
#                                  asset a sponsor checks; the others are
#                                  convenience.
#   *_all.deb                      so that someone can install today, months
#                                  before the archive has it.
#   SHA256SUMS, SHA256SUMS.asc     one signature covering everything above.
#
# Deliberately NOT GitHub's autogenerated tag tarball: it is produced by GitHub
# rather than by us, so it cannot carry our signature, and its bytes are
# GitHub's to change.
#
# Usage:
#   tools/release.sh              build, sign and verify; change nothing remote
#   tools/release.sh --publish    the above, then tag, push and publish

set -eu

here=$(cd "$(dirname "$0")/.." && pwd)
cd "$here"

pkg=hadith
publish=0
[ "${1:-}" = "--publish" ] && publish=1

full=$(dpkg-parsechangelog -l debian/changelog -S Version)   # 0.1.0-1
ver=${full%-*}                                              # 0.1.0
tag="v$ver"
repo=$(git config --get remote.origin.url | sed 's#.*[:/]\([^/]*/[^/]*\)\.git#\1#')

# The tag names the upstream version, not the Debian revision, because that is
# what uscan tracks. A Debian-only change (0.1.0-2) therefore reuses the same
# upstream tarball and needs no new tag -- refusing here is the correct answer
# to that case, not an obstacle to it.
if git rev-parse -q --verify "refs/tags/$tag" >/dev/null; then
	echo "error: tag $tag already exists." >&2
	echo "  A new Debian revision of the same upstream version reuses the" >&2
	echo "  published tarball and needs no release. If the upstream source" >&2
	echo "  really changed, bump the upstream version in debian/changelog." >&2
	exit 1
fi

if [ -n "$(git status --porcelain)" ]; then
	echo "error: working tree is not clean; the tarball would not match HEAD." >&2
	exit 1
fi

stage=${TMPDIR:-/tmp}/hadith-release-$ver
SIGN_ORIG=1 "$here/tools/build-deb.sh" "$stage" >/dev/null
echo "built and signed in $stage"

# The upstream name uscan expects. mk-origtargz renames it back to
# hadith_<ver>.orig.tar.gz on the way in; the signature is over the bytes and
# does not care what the file is called.
assets=$stage/assets
rm -rf "$assets"; mkdir -p "$assets"
cp "$stage/${pkg}_${ver}.orig.tar.gz"     "$assets/$pkg-$ver.tar.gz"
cp "$stage/${pkg}_${ver}.orig.tar.gz.asc" "$assets/$pkg-$ver.tar.gz.asc"
cp "$stage"/*_all.deb "$assets/"

(cd "$assets" && sha256sum ./* > SHA256SUMS.tmp && mv SHA256SUMS.tmp SHA256SUMS)
signer=$(dpkg-parsechangelog -l debian/changelog -S Maintainer | sed 's/.*<\(.*\)>.*/\1/')
gpg --armor --detach-sign --local-user "$signer" \
	--output "$assets/SHA256SUMS.asc" "$assets/SHA256SUMS"

# Verify against the key that ships in the packaging rather than against
# whatever happens to be in the local keyring -- that is the keyring a sponsor
# will use, so it is the one that has to work.
ring=$stage/verify.gpg
gpg --dearmor < debian/upstream/signing-key.asc > "$ring"
gpgv --keyring "$ring" "$assets/$pkg-$ver.tar.gz.asc" "$assets/$pkg-$ver.tar.gz"
gpgv --keyring "$ring" "$assets/SHA256SUMS.asc" "$assets/SHA256SUMS"
echo "signatures verify against debian/upstream/signing-key.asc"

lintian --profile debian --pedantic --fail-on error,warning \
	--suppress-tags newer-standards-version \
	"$stage"/${pkg}_${full}_*.changes
echo "lintian clean"

echo
echo "assets for $tag ($repo):"
ls -1 "$assets" | sed 's/^/  /'

if [ "$publish" = 0 ]; then
	echo
	echo "dry run -- nothing was tagged, pushed or published."
	echo "re-run with --publish to cut the release."
	exit 0
fi

command -v gh >/dev/null || { echo "error: gh not installed" >&2; exit 1; }
gh auth status >/dev/null 2>&1 || { echo "error: gh not authenticated" >&2; exit 1; }

git tag -s "$tag" -m "$pkg $ver"
git push origin "$tag"

# Draft first, then publish, so that the release:published event the CI
# verification job listens for cannot fire before the assets are attached.
gh release create "$tag" --draft --verify-tag \
	--title "$pkg $ver" \
	--notes "Upstream release $ver. The signed tarball is the packaging
source; the .debs are a convenience build of $full and are not an apt
repository, so they will not update themselves.

Verify:

    gpg --import debian/upstream/signing-key.asc
    gpg --verify SHA256SUMS.asc SHA256SUMS && sha256sum -c SHA256SUMS" \
	"$assets"/*
gh release edit "$tag" --draft=false
echo "published: https://github.com/$repo/releases/tag/$tag"
